export const OrderActionType = {
  ORDER_REQUEST_START: "ORDER_REQUEST_START",
  ORDER_REQUEST_SUCEES: "ORDER_REQUEST_SUCEES",
  ORDER_REQUEST_FAILED: "ORDER_REQUEST_FAILED",

  ORDER_DETAIL_REQUEST_START: "ORDER_DETAIL_REQUEST_START",
  ORDER_DETAIL_REQUEST_SUCEES: "ORDER_DETAIL_REQUEST_SUCEES",
  ORDER_DETAIL_REQUEST_FAILED: "ORDER_DETAIL_REQUEST_FAILED",

  ORDER_PAY_REQUEST_START: "ORDER_PAY_REQUEST_START",
  ORDER_PAY_REQUEST_SUCEES: "ORDER_PAY_REQUEST_SUCEES",
  ORDER_PAY_REQUEST_FAILED: "ORDER_PAY_REQUEST_FAILED",

  ORDER_PAY_RESET: "ORDER_PAY_RESET",

  ORDER_LIST_MY_REQUEST_START: "ORDER_LIST_MY_REQUEST_START",
  ORDER_LIST_MY_REQUEST_SUCCESS: "ORDER_LIST_MY_REQUEST_SUCCESS",
  ORDER_LIST_MY_REQUEST_FAILURE: "ORDER_LIST_MY_REQUEST_FAILURE",
};
