export const OrderActionType = {
  ORDER_REQUEST_START: "ORDER_REQUEST_START",
  ORDER_REQUEST_SUCEES: "ORDER_REQUEST_SUCEES",
  ORDER_REQUEST_FAILED: "ORDER_REQUEST_FAILED",

  ORDER_DETAIL_REQUEST_START: "ORDER_DETAIL_REQUEST_START",
  ORDER_DETAIL_REQUEST_SUCEES: "ORDER_DETAIL_REQUEST_SUCEES",
  ORDER_DETAIL_REQUEST_FAILED: "ORDER_DETAIL_REQUEST_FAILED",

  ORDER_PAY_REQUEST_START: "ORDER_PAY_REQUEST_START",
  ORDER_PAY_REQUEST_SUCEES: "ORDER_PAY_REQUEST_SUCEES",
  ORDER_PAY_REQUEST_FAILED: "ORDER_PAY_REQUEST_FAILED",

  ORDER_DELIVER_REQUEST_START: "ORDER_DELIVER_REQUEST_START",
  ORDER_DELIVER_REQUEST_SUCEES: "ORDER_DELIVER_REQUEST_SUCEES",
  ORDER_DELIVER_REQUEST_FAILED: "ORDER_DELIVER_REQUEST_FAILED",
  ORDER_DELIVER_RESET: "ORDER_DELIVER_RESET",

  ORDER_PAY_RESET: "ORDER_PAY_RESET",

  ORDER_LIST_MY_REQUEST_START: "ORDER_LIST_MY_REQUEST_START",
  ORDER_LIST_MY_REQUEST_SUCCESS: "ORDER_LIST_MY_REQUEST_SUCCESS",
  ORDER_LIST_MY_REQUEST_FAILURE: "ORDER_LIST_MY_REQUEST_FAILURE",

  GET_ALL_ORDER_START: "GET_ALL_ORDER_START",
  GET_ALL_ORDER_SUCCESS: "GET_ALL_ORDER:SUCCESS",
  GET_ALL_ORDER_FAIL: "GET_ALL_ORDER:FAIL",
};
