export const ProductActionType = {
  FETCH_PRODUCT_LIST_REQUEST_START: "FETCH_PRODUCT_LIST_REQUEST_START",
  PRODUCT_LIST_FETCH_SUCCESS: "PRODUCT_LIST_FETCH_SUCCESS",
  PRODUCT_LIST_FETCH_FAILURE: "PRODUCT_LIST_FETCH_FAILURE",

  SINGLE_PRODUCT_FETCH_START: "SINGLE_PRODUCT_FETCH_START",
  SINGLE_PRODUCT_FETCH_SUCCESS: "SINGLE_PRODUCT_FETCH_SUCCESS",
  SINGLE_PRODUCT_FETCH_FAILURE: "SINGLE_PRODUCT_FETCH_FAILURE",
};
