export const ProductActionType = {
  FETCH_PRODUCT_LIST_REQUEST_START: "FETCH_PRODUCT_LIST_REQUEST_START",
  PRODUCT_LIST_FETCH_SUCCESS: "PRODUCT_LIST_FETCH_SUCCESS",
  PRODUCT_LIST_FETCH_FAILURE: "PRODUCT_LIST_FETCH_FAILURE",

  SINGLE_PRODUCT_FETCH_START: "SINGLE_PRODUCT_FETCH_START",
  SINGLE_PRODUCT_FETCH_SUCCESS: "SINGLE_PRODUCT_FETCH_SUCCESS",
  SINGLE_PRODUCT_FETCH_FAILURE: "SINGLE_PRODUCT_FETCH_FAILURE",

  PRODUCT_DELETE_START: "PRODUCT_DELETE_START",
  PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
  PRODUCT_DELETE_FAIL: "PRODUCT_DELETE_FAIL",

  PRODUCT_CREATE_START: "PRODUCT_DELETE_START",
  PRODUCT_CREATE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
  PRODUCT_CREATE_FAIL: "PRODUCT_DELETE_FAIL",
  PRODUCT_CREATE_RESET: "PRODUCT_CREATE_RESET",

  PRODUCT_UPDATE_START: "PRODUCT_UPDATE_START",
  PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",
  PRODUCT_UPDATE_FAIL: "PRODUCT_UPDATE_FAIL",
  PRODUCT_UPDATE_RESET: "PRODUCT_UPDATE_RESET",
};
