export const UserActionType = {
  USER_LOGIN_REQUEST_START: "USER_LOGIN_REQUEST_START",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_REQUEST_FAILURE: "USER_LOGIN_REQUEST_FAILURE",

  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",
  USER_LOGOUT_START: "USER_LOGOUT_START",

  USER_REGISTER_REQUEST_START: "USER_REGISTER_REQUEST_START",
  USER_REGISTER_REQUEST_SUCCESS: "USER_REGISTER_REQUEST_SUCCESS",
  USER_REGISTER_REQUEST_FAILURE: "USER_REGISTER_REQUEST_FAILURE",

  USER_DETAILS_REQUEST_START: "USER_DETAILS_REQUEST_START",
  USER_DETAILS_REQUEST_SUCCESS: "USER_DETAILS_REQUEST_SUCCESS",
  USER_DETAILS_REQUEST_FAILURE: "USER_DETAILS_REQUEST_FAILURE",

  USER_PROFILE_UPDATE_REQ_START: "USER_PROFILE_UPDATE_REQ_START",
  USER_PROFILE_UPDATE_REQ_SUCEESS: "USER_PROFILE_UPDATE_REQ_SUCEESS",
  USER_PROFILE_UPDATE_REQ_FAILURE: "USER_PROFILE_UPDATE_REQ_FAILURE",

  USER_LIST_REQ_SUCEESS: "USER_LIST_REQ_SUCCESS",
  USER_LIST_REQ_FAILURE: "USER_LIST_REQ_FAILURE",
  USER_LIST_REQ_START: "USER_LIST_REQ_START",
  USER_LIST_RESET: "USER_LIST_RESET",

  USER_DELETE_START: "USER_DELETE_START",
  USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
  USER_DELETE_FAILURE: "USER_DELETE_FAILURE",

  USER_UPDATE_START: "USER_UPDATE_START",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCEESS",
  USER_UPDATE_FAILURE: "USER_UPDATE_FAILURE",
  USER_UPDATE_RESET: "USER_UPDATE_RESET",

  USER_UPDATE_REQUEST_START: "USER_UPDATE_REQUEST_START",
  USER_UPDATE_REQUEST_SUCCESS: "USER_UPDATE_REQUEST_SUCCESS",
  USER_UPDATE_REQUEST_FAIL: "USER_UPDATE_REQUEST_FAIL",
};
