export const UserActionType = {
  USER_LOGIN_REQUEST_START: "USER_LOGIN_REQUEST_START",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_REQUEST_FAILURE: "USER_LOGIN_REQUEST_FAILURE",

  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",
  USER_LOGOUT_START: "USER_LOGOUT_START",

  USER_REGISTER_REQUEST_START: "USER_REGISTER_REQUEST_START",
  USER_REGISTER_REQUEST_SUCCESS: "USER_REGISTER_REQUEST_SUCCESS",
  USER_REGISTER_REQUEST_FAILURE: "USER_REGISTER_REQUEST_FAILURE",
};
